tmpy.lo: /home/istrone/lab/php-5.3.10/ext/tmpy/tmpy.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/istrone/lab/php-5.3.10/ext/tmpy $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/istrone/lab/php-5.3.10/ext/tmpy/tmpy.c -o tmpy.lo 
$(phplibdir)/tmpy.la: ./tmpy.la
	$(LIBTOOL) --mode=install cp ./tmpy.la $(phplibdir)

./tmpy.la: $(shared_objects_tmpy) $(TMPY_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_tmpy) $(TMPY_SHARED_LIBADD)

