first_ext.lo: /home/istrone/lab/php-5.3.10/ext/first_ext/first_ext.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/istrone/lab/php-5.3.10/ext/first_ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/istrone/lab/php-5.3.10/ext/first_ext/first_ext.c -o first_ext.lo 
$(phplibdir)/first_ext.la: ./first_ext.la
	$(LIBTOOL) --mode=install cp ./first_ext.la $(phplibdir)

./first_ext.la: $(shared_objects_first_ext) $(FIRST_EXT_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_first_ext) $(FIRST_EXT_SHARED_LIBADD)

